task:
  name: build
  osx_instance:
    image: mojave-base
  environment:
    PASSWORD: ENCRYPTED[18b99f4d21d768a07511358c3d3581891567a74a29a25ab9299505b4ae14f6e769534bc60630f866f29795baf3348959]
  install_script:
    - brew install python3 
    - pip3 install --upgrade setuptools wheel
    - pip3 install pip==18.1
    - pip3 install pyinstaller
    - pip3 install -r requirements.txt
  build_script:
    - pyinstaller --noconfirm --onefile eccc.py
  publish_script:
    - curl -T dist/eccc -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/eccc/mac/
  
