osx_instance:
    image: mojave-base
environment:
    PASSWORD: ENCRYPTED[49d1196e18e8e95b75a7068276ac082aeccdbd45f48d4dfeb3581d54d6facd4ac4e87e64149bf81ec7cff36cd497a6a4]

build_task:
  install_script:
    - brew install python3 
    - pip3 install --upgrade setuptools wheel
    - pip3 install pip==18.1
    - pip3 install pyinstaller
    - pip3 install -r requirements.txt
  build_script:
    - pyinstaller --noconfirm --onefile ec3.py

publish_task:
  depends_on: 
    - build 
  only_if: $CIRRUS_BRANCH == 'master'
  script:
    - curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/mac/
  
