stages:
  - build
  - deploy

.build: &build
  image: docker:stable
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
    FF_NETWORK_PER_BUILD: "true"
  services:
    - docker:dind
  stage: build
  before_script:
    - docker info
  script:
    - docker run --rm -v "$(pwd):/src/" ${CONTAINER} "apt-get update -y && apt-get install -y upx-ucl && pyinstaller --noconfirm --onefile --additional-hooks-dir=.misc/hooks ec3.py"
  artifacts:
    expire_in: 1h
    paths:
      - dist/*

build-win:
  <<: *build
  variables:
    CONTAINER: lewisoaten/pyinstaller-windows:python3.7

build-lin:
  <<: *build
  variables:
    CONTAINER: cdrx/pyinstaller-linux:python3

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache curl ca-certificates
    - curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/lin/
    - curl -T dist/ec3.exe -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/win/
  only:
  - master

