conda:
  trigger:
    include: .conda-gitlab-ci.yml
    
pyinstaller lin:
  trigger:
    include: .pyinstaller-lin-gitlab-ci.yml
    
pyinstaller win:
  trigger:
    include: .pyinstaller-win-gitlab-ci.yml
