.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

pyinstaller_build win:
  image: docker:19.03.0
  stage: build
  services:
    - docker:19.03.0-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
  script:
    - docker run -v "$PWD:/src" batonogov/pyinstaller-windows
  artifacts:
    expire_in: 1h
    paths:
      - dist/*

pyinstaller_test win:
  extends:
    - .shared_windows_runners
  stage: test
  script:
    - dist/ec3.exe --version
    - dist/ec3.exe inv
  dependencies:
    - pyinstaller_build win
    
pyinstaller_deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache curl ca-certificates
    - curl -T dist/ec3.exe -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/win/
  dependencies:
    - pyinstaller_build win
  only:
  - master
