pyinstaller_build lin:
  image: python:3.9
  stage: build
  script:
    - apt -y update && apt install -y upx-ucl
    - pip install --upgrade pip setuptools wheel
    - pip install pyinstaller
    - pip install -r requirements.txt
    - pyinstaller ec3.spec
  artifacts:
    expire_in: 1h
    paths:
      - dist/*

pyinstaller_test lin:
  stage: test
  image: debian:bullseye-slim
  script:
    - chmod +x dist/ec3
    - dist/ec3 --version
    - dist/ec3 inv
  dependencies:
    - pyinstaller_build lin
    
pyinstaller_deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache curl ca-certificates
    - curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/lin/
  dependencies:
    - pyinstaller_build lin
  only:
  - main
