language: generic

os: osx

install:
    - |
      pip3 install --upgrade pip
      pip3 install pyinstaller
      pip3 install -r requirements.txt

script:
  - python -m pyinstaller --noconfirm --onefile eccc.py

addons:
  artifacts:
    # ...
    paths:
    - dist/*
