language: generic
os: osx
install:
- brew update
- brew upgrade python
- brew install upx
- pip3 install --upgrade pip setuptools wheel
- pip3 install pyinstaller
- pip3 install -r requirements.txt
script:
- pyinstaller --noconfirm --onefile ec3.py
after_success:
- if [ ${TRAVIS_BRANCH} == "master" ]; then curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/mac/; fi
