language: generic
os: osx
osx_image: xcode8
install:
- brew update
- brew upgrade python
- brew install upx
- pip3 install --upgrade setuptools wheel
- pip3 install pip==18.1
- pip3 install pyinstaller
- pip3 install -r requirements.txt
script:
- pyinstaller --noconfirm --onefile --additional-hooks-dir=.misc/hooks ec3.py
after_success:
- |
  if [ ${TRAVIS_BRANCH} == "master" ]; then
    curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/mac/
  else
    curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/testing/mac/
  fi
