language: generic
os: osx
osx_image: xcode12.5
install:
- brew update
- brew install upx
- travis_retry pip3 install --upgrade pip setuptools wheel
- travis_retry pip3 install pyinstaller
- travis_retry pip3 install -r requirements.txt
script:
- pyinstaller --noconfirm --onefile ec3.py
after_success:
- if [ ${TRAVIS_BRANCH} == "master" ]; then curl -T dist/ec3 -u "TSs69CZizMK6umjx:${PASSWORD}" https://dav.conr.ca/ec3/mac/; fi
