{% set version = "2.2.0" %}

package:
  name: ec3
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 1001
  script: "pip install ."

requirements:
  host:
    - "python>=3.7.1"
    - pip
    - docopt
    - geopy
    - pandas
    - requests
    - tqdm
  run:
    - "python>=3.7.1"
    - docopt
    - geopy
    - pandas
    - requests
    - tqdm

test:
  imports:
    - ec3

about:
  home: https://gitlab.com/ConorIA/ec3.py
  license: GPL-3
  summary: Program to search for and download historical Canadian climate
    data from Environment and Climate Change Canada's historical data archive.
  license_family: GPL3
    
extra:
  recipe-maintainers:
    - ConorIA
